apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: python-kube-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: python-kube-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: python-kube-clusterrole
  apiGroup: rbac.authorization.k8s.io