apiVersion: v1
kind: ConfigMap
metadata:
  name: python-configmap
  namespace: "default"
data:
  AWS_ACCESS_KEY_ID: {{ .Values.dankuni.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.dankuni.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-north-1"