apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
        network: web
    spec:
      serviceAccountName: python-kube-serviceaccount
      containers:
      - name: python-application
        image: 361769558926.dkr.ecr.us-east-1.amazonaws.com/application:{{ .Values.dankuni.VERSION }}
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: python-configmap
        resources:
          requests:
            cpu: "200m"          
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"

