apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
        network: web
    spec:
      containers:
      - name: python-application
        image: 058264138725.dkr.ecr.us-east-1.amazonaws.com/python-application:{{ .Values.dankuni.VERSION }}
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: python-secret
          - configMapRef:
              name: python-config
        resources:
          requests:
            cpu: "200m"          
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"

