name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main  
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264138725.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t python-application:latest .

      - name: Tag Docker image for ECR
        run: |
          docker tag python-application:latest 058264138725.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push 058264138725.dkr.ecr.us-east-1.amazonaws.com/python-application:latest
