name: Deploy Helm Chart to EKS

on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'version of the docker image to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.8.1'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name popupq

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install application ./infrastructure/helm/dankuni --set dankuni.VERSION=${{ github.event.inputs.IMAGE_VERSION }}
        env:
          VERSION: ${{ github.event.inputs.IMAGE_VERSION }}
